### ISSUE TITLE
Error on build. Undefined symbol: _AVAudioSession

### ISSUE THREAD

**Issue by ielonclesio** [react-native-webrtc/react-native-callkeep#426]
# Bug report

- [ X ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [ X ] iOS

## Description
Error on Build:
Undefined symbol: _AVAudioSessionInterruptionTypeKey
Undefined symbol: _AVAudioSessionInterruptionOptionKey
Undefined symbol: _AVAudioSessionInterruptionNotification
Undefined symbol: _AVAudioSessionCategoryPlayAndRecord
Undefined symbol: _AVAudioSessionModeVoiceChat
Undefined symbol: _OBJC_CLASS_$_AVAudioSession

## Steps to Reproduce
Build in XCode 12.5

## Versions
    - Callkeep: 4.0.1
    - React Native: 0.61.2
    - iOS: 12
    - Android:
    - Phone model: iPhone 6

## Logs
Undefined symbols for architecture armv7:
  "_AVAudioSessionInterruptionTypeKey", referenced from:
      -[RNCallKeep provider:didActivateAudioSession:] in RNCallKeep.o
  "_AVAudioSessionInterruptionOptionKey", referenced from:
      -[RNCallKeep provider:didActivateAudioSession:] in RNCallKeep.o
  "_AVAudioSessionInterruptionNotification", referenced from:
      -[RNCallKeep provider:didActivateAudioSession:] in RNCallKeep.o
  "_AVAudioSessionCategoryPlayAndRecord", referenced from:
      -[RNCallKeep configureAudioSession] in RNCallKeep.o
  "_AVAudioSessionModeVoiceChat", referenced from:
      -[RNCallKeep configureAudioSession] in RNCallKeep.o
  "_OBJC_CLASS_$_AVAudioSession", referenced from:
      objc-class-ref in RNCallKeep.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by txtasad** [comment]
any update here? my build failing with same error.

**Comment by namnm** [comment]
May be related to this? https://stackoverflow.com/questions/54515175

1st answer:
Make sure JavaScriptCore.framework is added to Link Binary With Libraries

Or just remove the arm build if you dont need to support arm:
Select your project name in the project navigator
Select your target that is having this issue
Find "Valid Architectures" under "Build Setting" > "Architectures"
Remove "arm64 & arm7" from "Valid Architectures" from the relevant scheme

**Comment by christopher-18** [comment]
Hey, any update for this. Facing same issue while running on xCode 13.

**Comment by kekami** [comment]
Hello, we are also experiencing this issue.
Adding JavaScriptCore.framework to Link Binary With Libraries does not resolve it.

Xcode 13.1 on Apple Silicon M1

**Comment by dhayaljaswantgit** [comment]
> Hello, we are also experiencing this issue. Adding JavaScriptCore.framework to Link Binary With Libraries does not resolve it.
> 
> Xcode 13.1 on Apple Silicon M1

I'M also facing this on *Xcode 13.1 on Apple Silicon M1* , how you resolved that?
